[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:pkg_resources is deprecated as an API\.:UserWarning
    ignore:Deprecated call to `pkg_resources\.declare_namespace\(.*\)`\.:DeprecationWarning
    ignore:'audioop' is deprecated and slated for removal in Python 3\.13:DeprecationWarning
