from types import SimpleNamespace

import pytest
from peewee import IndexMetadata, PostgresqlDatabase, SqliteDatabase

from efb_telegram_master.db import DatabaseManager
from efb_telegram_master.legacy_outbound_retirement import LegacyOutboundRetirement
from efb_telegram_master.persistence import database_initializer
from tests.support.legacy_outbound_schema import create_legacy_outbound_schema


def test_startup_preserves_non_empty_legacy_outbound_tables(tmp_path, monkeypatch):
    database_path = tmp_path / "tgdata.db"
    raw_db = SqliteDatabase(database_path)
    raw_db.connect()
    try:
        workflow, task = create_legacy_outbound_schema(raw_db)
        workflow.create()
        task.create(
            source_key="source",
            target_chat_id=1,
            operation="send_message",
            payload="secret",
            workflow_id=1,
        )
    finally:
        raw_db.close()

    monkeypatch.setattr(database_initializer.utils, "get_data_path", lambda _channel_id: tmp_path)
    try:
        with pytest.raises(RuntimeError, match="automatic replay is disabled"):
            DatabaseManager(SimpleNamespace(channel_id="tests.legacy", config=SimpleNamespace(database={})))
        preserved_db = SqliteDatabase(database_path)
        preserved_db.connect()
        try:
            assert set(LegacyOutboundRetirement.TABLES).issubset(preserved_db.get_tables())
            assert preserved_db.execute_sql("SELECT COUNT(*) FROM outboundworkflow").fetchone()[0] == 1
            assert preserved_db.execute_sql("SELECT COUNT(*) FROM outboundtask").fetchone()[0] == 1
        finally:
            preserved_db.close()
    finally:
        pass


@pytest.mark.parametrize(
    ("table_name", "column_name", "data_type", "primary_key", "default", "expected"),
    (
        ("outboundworkflow", "id", "integer", True, None, "auto_pk"),
        ("outboundworkflow", "id", "integer", True, "nextval('outboundworkflow_id_seq'::regclass)", "auto_pk"),
        ("outboundtask", "id", "integer", True, "nextval('public.outboundtask_id_seq'::regclass)", "auto_pk"),
        ("outboundtask", "id", "integer", True, 'nextval(\'"public"."outboundtask_id_seq"\'::regclass)', "auto_pk"),
        ("outboundtask", "id", "integer", True, " ( NEXTVAL ( '\"outboundtask_id_seq\"' :: REGCLASS ) ) ", "auto_pk"),
        ("outboundtask", "id", "integer", True, "nextval('outboundworkflow_id_seq'::regclass)", "invalid:nextval('outboundworkflow_id_seq'::regclass)"),
        ("outboundtask", "id", "integer", True, "nextval('evil.outboundtask_id_seq'::regclass)", "invalid:nextval('evil.outboundtask_id_seq'::regclass)"),
        ("outboundtask", "id", "integer", True, "nextval('outboundtask_id_seq'::text::regclass)", "invalid:nextval('outboundtask_id_seq'::text::regclass)"),
        ("outboundtask", "state", "text", False, "nextval('outboundtask_id_seq'::regclass)", "invalid:nextval('outboundtask_id_seq'::regclass)"),
        ("outboundtask", "id", "integer", True, "generated by default as identity", "invalid:generated by default as identity"),
    ),
)
def test_legacy_auto_primary_key_default_categories(table_name, column_name, data_type, primary_key, default, expected):
    backend = SqliteDatabase(":memory:") if default is None else PostgresqlDatabase("tests")
    assert LegacyOutboundRetirement._default_category(backend, table_name, column_name, data_type, primary_key, default) == expected


def test_postgresql_legacy_outbound_index_fixture_excludes_only_the_primary_key_index(monkeypatch):
    backend = PostgresqlDatabase("tests")
    introspected_indexes = (
        IndexMetadata("outboundtask_pkey", "CREATE UNIQUE INDEX outboundtask_pkey ON outboundtask (id)", ["id"], True, "outboundtask"),
        IndexMetadata(
            "outboundtask_workflow_id_step_index",
            "CREATE UNIQUE INDEX outboundtask_workflow_id_step_index ON outboundtask (workflow_id, step_index)",
            ["workflow_id", "step_index"],
            True,
            "outboundtask",
        ),
        IndexMetadata(
            "outboundtask_source_key_priority_accepted_at_id",
            "CREATE INDEX outboundtask_source_key_priority_accepted_at_id ON outboundtask (source_key, priority, accepted_at, id)",
            ["source_key", "priority", "accepted_at", "id"],
            False,
            "outboundtask",
        ),
        IndexMetadata("outboundtask_state_available_at", "CREATE INDEX outboundtask_state_available_at ON outboundtask (state, available_at)", ["state", "available_at"], False, "outboundtask"),
        IndexMetadata("outboundtask_workflow_id", "CREATE INDEX outboundtask_workflow_id ON outboundtask (workflow_id)", ["workflow_id"], False, "outboundtask"),
    )
    monkeypatch.setattr(backend, "get_indexes", lambda _table_name: introspected_indexes)

    assert set(LegacyOutboundRetirement.task_indexes(backend)) == set(LegacyOutboundRetirement._TASK_INDEXES)

    monkeypatch.setattr(backend, "get_indexes", lambda _table_name: (*introspected_indexes, IndexMetadata("outboundtask_unexpected", "", ["state"], False, "outboundtask")))

    assert set(LegacyOutboundRetirement.task_indexes(backend)) != set(LegacyOutboundRetirement._TASK_INDEXES)


@pytest.mark.parametrize("legacy_table", LegacyOutboundRetirement.TABLES)
def test_startup_aborts_without_dropping_partial_historical_schema(tmp_path, monkeypatch, legacy_table):
    raw_db = SqliteDatabase(tmp_path / "tgdata.db")
    raw_db.connect()
    try:
        create_legacy_outbound_schema(raw_db, tables=(legacy_table,))
    finally:
        raw_db.close()

    monkeypatch.setattr(database_initializer.utils, "get_data_path", lambda _channel_id: tmp_path)
    try:
        with pytest.raises(RuntimeError, match="partial-schema collision"):
            DatabaseManager(SimpleNamespace(channel_id=f"tests.partial-{legacy_table}", config=SimpleNamespace(database={})))
        collision_db = SqliteDatabase(tmp_path / "tgdata.db")
        collision_db.connect()
        try:
            assert legacy_table in collision_db.get_tables()
        finally:
            collision_db.close()
    finally:
        pass


def test_startup_aborts_without_dropping_same_named_schema_collision(tmp_path, monkeypatch):
    raw_db = SqliteDatabase(tmp_path / "tgdata.db")
    raw_db.connect()
    try:
        raw_db.execute_sql("CREATE TABLE outboundworkflow (id INTEGER PRIMARY KEY, unrelated TEXT)")
        create_legacy_outbound_schema(raw_db, tables=("outboundtask",))
    finally:
        raw_db.close()

    monkeypatch.setattr(database_initializer.utils, "get_data_path", lambda _channel_id: tmp_path)
    try:
        with pytest.raises(RuntimeError, match="Legacy outbound schema collision"):
            DatabaseManager(SimpleNamespace(channel_id="tests.collision", config=SimpleNamespace(database={})))
        collision_db = SqliteDatabase(tmp_path / "tgdata.db")
        collision_db.connect()
        try:
            assert "outboundworkflow" in collision_db.get_tables()
        finally:
            collision_db.close()
    finally:
        pass


@pytest.mark.parametrize(
    ("table_name", "column_name"),
    (
        ("outboundworkflow", "created_at"),
        ("outboundtask", "state"),
    ),
)
def test_startup_refuses_legacy_tables_with_default_collisions(tmp_path, monkeypatch, table_name, column_name):
    raw_db = SqliteDatabase(tmp_path / "tgdata.db")
    raw_db.connect()
    try:
        create_legacy_outbound_schema(raw_db)
        table_sql = raw_db.execute_sql("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", (table_name,)).fetchone()[0]
        index_sql = [row[0] for row in raw_db.execute_sql("SELECT sql FROM sqlite_master WHERE type = 'index' AND tbl_name = ? AND sql IS NOT NULL", (table_name,)).fetchall()]
        raw_db.execute_sql(f'DROP TABLE "{table_name}"')
        expected_default = "DEFAULT CURRENT_TIMESTAMP" if column_name == "created_at" else ""
        changed_sql = (
            table_sql.replace(f'"{column_name}" DATETIME NOT NULL {expected_default}', f"\"{column_name}\" DATETIME NOT NULL DEFAULT 'unexpected'")
            if column_name == "created_at"
            else table_sql.replace(f'"{column_name}" TEXT NOT NULL', f"\"{column_name}\" TEXT NOT NULL DEFAULT 'unexpected'")
        )
        raw_db.execute_sql(changed_sql)
        for statement in index_sql:
            raw_db.execute_sql(statement)
    finally:
        raw_db.close()

    monkeypatch.setattr(database_initializer.utils, "get_data_path", lambda _channel_id: tmp_path)
    try:
        with pytest.raises(RuntimeError, match="schema collision"):
            DatabaseManager(SimpleNamespace(channel_id=f"tests.defaults-{table_name}", config=SimpleNamespace(database={})))
        collision_db = SqliteDatabase(tmp_path / "tgdata.db")
        collision_db.connect()
        try:
            assert set(LegacyOutboundRetirement.TABLES).issubset(collision_db.get_tables())
        finally:
            collision_db.close()
    finally:
        pass


def test_startup_refuses_altered_accepted_at_default_without_dropping_legacy_schema(tmp_path, monkeypatch):
    database_path = tmp_path / "tgdata.db"
    raw_db = SqliteDatabase(database_path)
    raw_db.connect()
    try:
        workflow, task = create_legacy_outbound_schema(raw_db)
        task_sql = raw_db.execute_sql("SELECT sql FROM sqlite_master WHERE type = 'table' AND name = ?", ("outboundtask",)).fetchone()[0]
        index_sql = [row[0] for row in raw_db.execute_sql("SELECT sql FROM sqlite_master WHERE type = 'index' AND tbl_name = ? AND sql IS NOT NULL", ("outboundtask",)).fetchall()]
        raw_db.execute_sql("DROP TABLE outboundtask")
        raw_db.execute_sql(task_sql.replace("DEFAULT CURRENT_TIMESTAMP", "DEFAULT 'unexpected'"))
        for statement in index_sql:
            raw_db.execute_sql(statement)
        task.create(source_key="source", target_chat_id=1, operation="send_message", payload="secret", workflow_id=1)
    finally:
        raw_db.close()

    monkeypatch.setattr(database_initializer.utils, "get_data_path", lambda _channel_id: tmp_path)
    try:
        with pytest.raises(RuntimeError, match="schema collision"):
            DatabaseManager(SimpleNamespace(channel_id="tests.accepted-at-default", config=SimpleNamespace(database={})))
        collision_db = SqliteDatabase(database_path)
        collision_db.connect()
        try:
            assert set(LegacyOutboundRetirement.TABLES).issubset(collision_db.get_tables())
            assert collision_db.execute_sql("SELECT COUNT(*) FROM outboundworkflow").fetchone()[0] == 0
            assert collision_db.execute_sql("SELECT COUNT(*) FROM outboundtask").fetchone()[0] == 1
            assert {index.name for index in collision_db.get_indexes("outboundtask")} == {
                "outboundtask_source_key_priority_accepted_at_id",
                "outboundtask_state_available_at",
                "outboundtask_workflow_id",
                "outboundtask_workflow_id_step_index",
            }
        finally:
            collision_db.close()
    finally:
        pass
