name: Sync to Sub-Account

on:
  push:
    branches: [ "dev" ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Clean up files
        run: |
          rm -rf .git
          rm -rf .github

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'onestao'
          destination-repository-name: 'efb-telegram-master'
          user-email: 'kettly1266@gmail.com'
          target-branch: main
          # 【新增下面这一行】：强制写死提交信息，绝对不带大号的任何痕迹
          commit-message: 'Auto sync latest code'
